#
# Boot Shim Configs for Miatoll (Redmi Note 9S)
#

# Required for ABL/Bootloader compatibility
TARGET_REQUIRES_KERNEL_HEADER=1

# UEFI Memory Placement (Moving away from 0x9FD00000)
# 0x80000000 is the safest start of system RAM
TARGET_FD_BASE=0x80000000
TARGET_FD_SIZE=0x00300000

# Feature Flags
# Ensure these match your Pcd definitions in the .dsc file
PcdEnableVHE=1
PcdPrePiStackBase=0x81000000
PcdPrePiStackSize=0x00040000

