name: Build UEFI for Lime

on:
  workflow_dispatch: # Manuel tetikleme butonu

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

            - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential uuid-dev iasl git nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pip clang-12 llvm-12
          python3 -m pip install --upgrade pip
          # We removed the problematic 'mono-cache' and added essential EDK2 tools
          python3 -m pip install edk2-pytool-extensions edk2-pytool-library antlr4-python3-runtime --break-system-packages

          fi

      - name: Build UEFI for Lime
        run: |
          export EDK2_THREADS=$(nproc)
          bash build_uefi.sh -d lime

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lime-UEFI-Output
          path: |
            workspace/Build/Xiaomi/limePkg/DEBUG_CLANG38/FV/*.fd
            workspace/Build/Xiaomi/limePkg/RELEASE_CLANG38/FV/*.fd
            *.img
